Remove UB from definition of symbols in i915_reg.h
Kernel Undefined Behavior Sanitizer enforces more warnings in build time.
This makes the build fatal in the drm/i915 code in:
 - intel_ddi_put_crtc_pll(),
 - intel_ddi_clock_get(),
 - intel_ddi_pll_enable(),
 - intel_ddi_setup_hw_pll_state().

The error message in all the cases says:

  error: case label does not reduce to an integer constant

Set the type of the value left shifted to unsigned.

This change is required to build NetBSD/amd64 with KUBSan.